name: CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -r Textrepeater/requirements.txt
      - name: Run tests
        working-directory: Textrepeater
        run: pytest -q

  build-and-deploy:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT || '3306' }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME || 'textrepeater' }}
      DB_SSL_MODE: REQUIRED
      FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies (build layer cache warmup)
        run: pip install -r Textrepeater/requirements.txt
      - name: Login to Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Zip deploy
        run: |
          cd Textrepeater
          zip -r app.zip . -x '*.pytest_cache*' -x '*.venv*'
          az webapp deploy --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_WEBAPP_NAME --src-path app.zip --type zip
      - name: Configure App Settings
        run: |
          az webapp config appsettings set --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_WEBAPP_NAME --settings \
            FLASK_SECRET_KEY="$FLASK_SECRET_KEY" \
            DB_HOST="$DB_HOST" DB_PORT="$DB_PORT" DB_USER="$DB_USER" DB_PASSWORD="$DB_PASSWORD" DB_NAME="$DB_NAME" DB_SSL_MODE="$DB_SSL_MODE"
      - name: Show WebApp URL
        run: |
          echo "App URL: https://$AZURE_WEBAPP_NAME.azurewebsites.net"
